version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Moscow
    open-pull-requests-limit: 10
    reviewers:
      - JarvisCraft
    labels:
      - automatic
      - dependencies
    allow:
      - dependency-type: direct
      - dependency-type: indirect

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: development
    reviewers:
      - JarvisCraft
    labels:
      - dependencies
      - automatic
